// ─── POST /api/schools/onboard ────────────────────────────────────────────────
// Creates the first class for a school during the onboarding wizard.
// Returns the new class's join_code so the wizard can display it on step 3.
//
// Auth: must be authenticated + have proprietor/admin role for the given schoolId.
// join_code is auto-generated by the DB trigger (20260420_class_join_codes.sql).
// ─────────────────────────────────────────────────────────────────────────────

import { NextResponse } from "next/server";
import { createClient }  from "@supabase/supabase-js";
import { cookies }       from "next/headers";
import { createServerClient } from "@supabase/ssr";

export async function POST(request) {
  try {
    const body = await request.json();
    const { schoolId, className, curriculum, yearLevel } = body;

    if (!schoolId || !className?.trim() || !curriculum || !yearLevel) {
      return NextResponse.json(
        { error: "schoolId, className, curriculum, and yearLevel are required." },
        { status: 400 },
      );
    }

    // ── Verify caller is a proprietor/admin for this school ──────────────────
    const cookieStore = await cookies();
    const userSupabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
      { cookies: { getAll: () => cookieStore.getAll() } },
    );
    const { data: { user } } = await userSupabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Authentication required." }, { status: 401 });
    }

    // Use service role for the actual writes
    const admin = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
    );

    const { data: role } = await admin
      .from("school_roles")
      .select("role")
      .eq("user_id",  user.id)
      .eq("school_id", schoolId)
      .in("role", ["proprietor", "admin"])
      .single();

    if (!role) {
      return NextResponse.json({ error: "Forbidden — not a proprietor for this school." }, { status: 403 });
    }

    // ── Create the class (join_code auto-set by trigger) ─────────────────────
    const { data: newClass, error: classErr } = await admin
      .from("classes")
      .insert({
        school_id:   schoolId,
        name:        className.trim(),
        curriculum,
        year_level:  yearLevel,
        academic_year: new Date().getFullYear().toString(),
      })
      .select("id, join_code")
      .single();

    if (classErr) {
      console.error("[onboard] class insert error:", classErr);
      return NextResponse.json({ error: classErr.message }, { status: 500 });
    }

    // ── Mark school onboarding complete ──────────────────────────────────────
    await admin
      .from("schools")
      .update({ onboarding_completed_at: new Date().toISOString() })
      .eq("id", schoolId);

    return NextResponse.json({
      classId:  newClass.id,
      joinCode: newClass.join_code,
    });

  } catch (err) {
    console.error("[onboard] error:", err);
    return NextResponse.json({ error: err.message || "Internal error." }, { status: 500 });
  }
}
